SELECT FI.ID AS ID, NI.FISH_NAME AS FISH_NAME, FI.LENGTH AS LENGTH
FROM FISH_INFO FI
JOIN FISH_NAME_INFO NI
ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE FI.LENGTH = (
        -- 물고기 종류 별 최댓값
        SELECT MAX(LENGTH) AS LENGTH
        FROM FISH_INFO FI2
        WHERE FI2.FISH_TYPE = FI.FISH_TYPE
)
ORDER BY FI.ID;